const { chromium } = require('@playwright/test');
(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('http://192.168.2.205:8080/login');
  await page.getByPlaceholder('Enter username').fill('default');
  await page.getByPlaceholder('Enter password').fill('admin');
  await page.getByRole('button', { name: /sign in/i }).click();
  await page.waitForURL('**/dashboard', { timeout: 10000 }).catch(() => {});
  await page.waitForTimeout(2000);
  await page.goto('http://192.168.2.205:8080/media');
  await page.waitForLoadState('networkidle').catch(() => {});
  await page.waitForTimeout(3000);
  console.log('URL:', page.url());
  console.log('TITLE:', await page.title());
  const headings = await page.$$eval('h1, h2, h3, h4, h5, h6', els => els.map(e => e.tagName + ': ' + e.textContent.trim()));
  console.log('HEADINGS:', JSON.stringify(headings));
  const body = await page.content();
  console.log('BODY PREVIEW (first 2000):', body.substring(0, 2000));
  await page.screenshot({ path: '/tmp/media-debug.png', fullPage: true });
  await browser.close();
  process.exit(0);
})();
