"""Per-user MA player scope for the browser JSON-RPC proxy (MEDIA_OVERHAUL §7.3).

The browser controls the house through WS /api/ma-jsonrpc using one shared MA
token, so Music Assistant cannot tell family members apart. This module adds
the missing check on the gateway side: every player/queue a frame references
must be one the caller may control according to Identity's device assignments
-- the same rules the execution service applies to HA entities
(``services.execution.entity_access``).

Physical MA players surface in Home Assistant as ``media_player.mass_<id>``
entities, so a referenced MA player/queue id maps onto that entity id and the
ordinary assignment/protection rules decide.

Browser web players are session-scoped and self-asserted: the id is random,
generated by the client (localStorage ``sendspin_webplayer_id``) and announced
on the sendspin WebSocket in ``client/hello``. The gateway records that id per
user when the engine connects and exempts exactly the recorded id, so a user
can always control their own speaker without being able to name someone else's
player as their own.
"""
from __future__ import annotations

import json
import logging

from services.execution.entity_access import load_entity_permissions
from services.gateway.ma_allowlist import forbidden_frame

log = logging.getLogger("gateway.ma_scope")

# user -> client_id announced on the user's sendspin connection. In-memory on
# purpose: the id is ephemeral (a page reload can mint a new one) and there is
# nothing durable to store.
_WEB_PLAYER_IDS: dict[str, str] = {}

# Argument names that carry a single player/queue reference in MA's JSON-RPC.
_PLAYER_REF_KEYS = ("player_id", "queue_id", "target_player", "source_queue_id", "target_queue_id")
# Argument names that carry a list of player references.
_PLAYER_REF_LIST_KEYS = ("child_player_ids",)

_SLUG_SAFE = frozenset("abcdefghijklmnopqrstuvwxyz0123456789_")


def record_web_player_id(user: str, client_id: str) -> None:
    """Remember the web player id the user's browser just announced."""
    if not user or not client_id:
        return
    _WEB_PLAYER_IDS[user] = client_id
    log.info("[ma-scope] Recorded web player id for %s", user)


def web_player_id_for(user: str) -> str | None:
    """The last web player id announced by this user's sendspin connection."""
    return _WEB_PLAYER_IDS.get(user)


def forget_web_player_ids() -> None:
    """Clear recordings (tests; a restart does the same in production)."""
    _WEB_PLAYER_IDS.clear()


def ma_entity_id(player_id: str) -> str:
    """Map an MA player id onto its Home Assistant entity id.

    HA slugifies integration entity ids (lowercase, non-alphanumerics become
    underscores), so "Office Display" and "sendspin-js" become
    ``media_player.mass_office_display`` / ``media_player.mass_sendspin_js``.
    """
    slug = "".join(ch if ch in _SLUG_SAFE else "_" for ch in player_id.strip().lower())
    return f"media_player.mass_{slug}"


def player_refs_in_frame(frame: dict) -> set[str]:
    """Every player/queue id a JSON-RPC frame references."""
    args = frame.get("args")
    if not isinstance(args, dict):
        return set()
    refs: set[str] = set()
    for key in _PLAYER_REF_KEYS:
        value = args.get(key)
        if isinstance(value, str) and value.strip():
            refs.add(value.strip())
    for key in _PLAYER_REF_LIST_KEYS:
        value = args.get(key)
        if isinstance(value, list):
            refs.update(
                item.strip() for item in value if isinstance(item, str) and item.strip()
            )
    return refs


async def check_ma_frame_scope(raw: str, *, user: str, is_admin: bool) -> str | None:
    """Return an error frame if the command references an out-of-scope player.

    Admins bypass. Frames without player references pass. A frame referencing
    only the caller's recorded web player id passes. Everything else is checked
    against Identity's assignments; when Identity is unreachable and has no
    cached answer the frame passes with a loud log, matching the
    availability-first rule used for HA entity control.
    """
    if is_admin:
        return None
    try:
        frame = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(frame, dict):
        return None

    refs = player_refs_in_frame(frame)
    own_web_player = web_player_id_for(user)
    if own_web_player:
        refs.discard(own_web_player)
    if not refs:
        return None

    perms = await load_entity_permissions(user)
    if perms is None:
        log.warning(
            "[ma-scope] ALLOW %s -> %s: Identity unreachable and no cached "
            "permissions — player scope cannot be enforced right now",
            user,
            sorted(refs),
        )
        return None

    denied = sorted(ref for ref in refs if not perms.may_control(ma_entity_id(ref)))
    if denied:
        log.info(
            "[ma-scope] DENIED %s -> %s (not assigned or not permitted)",
            user,
            denied,
        )
        return forbidden_frame(frame.get("message_id"))
    return None
