#!/usr/bin/env python3
"""DNS Sync Sidecar - Polls Identity for DNS mappings and updates dnsmasq."""
import os
import json
import time
import signal
import subprocess
from urllib.request import Request, urlopen

IDENTITY_URL = os.getenv("IDENTITY_SVC_URL", "http://identity:8001")
INTERNAL_SECRET = os.getenv("INTERNAL_SECRET", "")
DNS_CONF_PATH = os.getenv("DNS_CONF_PATH", "/etc/dnsmasq.conf")
POLL_INTERVAL = int(os.getenv("DNS_POLL_INTERVAL", "30"))
UPSTREAM_DNS = os.getenv("UPSTREAM_DNS", "8.8.8.8,1.1.1.1")

running = True

def handle_signal(signum, frame):
    global running
    running = False

signal.signal(signal.SIGTERM, handle_signal)
signal.signal(signal.SIGINT, handle_signal)

def fetch_dns_mappings():
    """Fetch DNS mappings from Identity settings."""
    try:
        req = Request(
            f"{IDENTITY_URL}/api/settings",
            headers={"X-Internal-Secret": INTERNAL_SECRET}
        )
        with urlopen(req, timeout=10) as resp:
            settings = json.loads(resp.read())
            for s in settings:
                if s["key"] == "dns_mappings":
                    return json.loads(s["value"]) if s["value"] else {}
    except Exception as e:
        print(f"[dns-sync] Error fetching settings: {e}", flush=True)
    return {}

def generate_dnsmasq_config(mappings):
    """Generate dnsmasq configuration from mappings."""
    lines = [
        "# Auto-generated by dns-sync sidecar",
        "# Do not edit manually - changes will be overwritten",
        "",
        "# Upstream DNS servers",
    ]
    for server in UPSTREAM_DNS.split(","):
        lines.append(f"server={server.strip()}")
    
    lines.append("")
    lines.append("# Local service mappings")
    for hostname, ip in mappings.items():
        if hostname and ip:
            lines.append(f"address=/{hostname}/{ip}")
    
    lines.append("")
    lines.append("# Don't forward local names")
    lines.append("local=/local/")
    lines.append("")
    
    return "\n".join(lines)

def reload_dnsmasq():
    """Send SIGHUP to dnsmasq to reload config."""
    try:
        subprocess.run(["pkill", "-HUP", "dnsmasq"], check=False)
        print("[dns-sync] Sent SIGHUP to dnsmasq", flush=True)
    except Exception as e:
        print(f"[dns-sync] Error reloading dnsmasq: {e}", flush=True)

def main():
    print(f"[dns-sync] Starting DNS sync sidecar (poll every {POLL_INTERVAL}s)", flush=True)
    last_config = None
    
    while running:
        mappings = fetch_dns_mappings()
        config = generate_dnsmasq_config(mappings)
        
        if config != last_config:
            try:
                with open(DNS_CONF_PATH, "w") as f:
                    f.write(config)
                last_config = config
                print(f"[dns-sync] Config updated with {len(mappings)} mappings", flush=True)
                reload_dnsmasq()
            except Exception as e:
                print(f"[dns-sync] Error writing config: {e}", flush=True)
        
        # Sleep in small increments to allow signal handling
        for _ in range(POLL_INTERVAL):
            if not running:
                break
            time.sleep(1)
    
    print("[dns-sync] Shutting down", flush=True)

if __name__ == "__main__":
    main()
